//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPORTS_STORE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartProduct
    {
        public int Id { get; set; }
        public int CartId { get; set; }
        public System.Guid ProductId { get; set; }
        public int Quantity { get; set; }
        public bool Ordered { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Product Product { get; set; }
    }
}
