//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPORTS_STORE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int CheckoutId { get; set; }
        public System.Guid ProductId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Checkout Checkout { get; set; }
    }
}
